// Ícones do app — Lucide (https://lucide.dev), com aliases semânticos.
export {
  LayoutDashboard as IconDashboard,
  List as IconList,
  Target as IconTarget,
  ArrowUp as IconArrowUp,
  ArrowDown as IconArrowDown,
  Plus as IconPlus,
  Minus as IconMinus,
  Pencil as IconEdit,
  Trash2 as IconTrash,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  X as IconX,
  Scale as IconScale,
  Calendar as IconCalendar,
  TrendingUp as IconTrendUp,
  Wallet as IconWallet,
  Sparkles as IconSparkle,
  Eye as IconEye,
  EyeOff as IconEyeOff,
  Tag as IconTag,
  PartyPopper as IconParty,
} from "lucide-react";
